// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4te3PL2udb_YKTuAwipc8qR9lxffdnhg',
    appId: '1:583341402697:web:02337f0df74be984d92d98',
    messagingSenderId: '583341402697',
    projectId: 'smarthostelmanagement01',
    authDomain: 'smarthostelmanagement01.firebaseapp.com',
    storageBucket: 'smarthostelmanagement01.firebasestorage.app',
    measurementId: 'G-710EZ491WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRU4RpFFWNYOVb3PUFXsEI2Z2CwqfYd8g',
    appId: '1:583341402697:android:279b30f8c5bccac1d92d98',
    messagingSenderId: '583341402697',
    projectId: 'smarthostelmanagement01',
    storageBucket: 'smarthostelmanagement01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUg_V8QKrwFZtUC3IDqZEV8763bUpJups',
    appId: '1:583341402697:ios:5dd146d097e44969d92d98',
    messagingSenderId: '583341402697',
    projectId: 'smarthostelmanagement01',
    storageBucket: 'smarthostelmanagement01.firebasestorage.app',
    iosBundleId: 'com.example.smartHostelMngment01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUg_V8QKrwFZtUC3IDqZEV8763bUpJups',
    appId: '1:583341402697:ios:5dd146d097e44969d92d98',
    messagingSenderId: '583341402697',
    projectId: 'smarthostelmanagement01',
    storageBucket: 'smarthostelmanagement01.firebasestorage.app',
    iosBundleId: 'com.example.smartHostelMngment01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4te3PL2udb_YKTuAwipc8qR9lxffdnhg',
    appId: '1:583341402697:web:92198f39fde85044d92d98',
    messagingSenderId: '583341402697',
    projectId: 'smarthostelmanagement01',
    authDomain: 'smarthostelmanagement01.firebaseapp.com',
    storageBucket: 'smarthostelmanagement01.firebasestorage.app',
    measurementId: 'G-CJP33MN35E',
  );

}